### PR TITLE
transfer current working document to github

### PR DESCRIPTION
**Pull request by TimoGlastra**
This is an exact copy (minus some typos) of the working document in HackMD. Will make an additional PR to clean up soon.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
BTW -- How does it work with maintainers and reviews? Is there someone responsible for reviewing these PRs?

**Comment by TimoGlastra** [comment]
@tmarkovski @nembal any idea on this?

**Review by tmarkovski — APPROVED** [review]
LGTM

**Comment by bumblefudge** [comment]
In the future, I think you're fine to self-push for stuff like this. As your assigned reviewer signed off, I'm just gonna merge myself in the interest of not having an empty repo a minute longer than necessary 😁

**Comment by TimoGlastra** [comment]
Thanks @bumblefudge!

I'm fine with self pushing however I have no maintainer rights on this repo. So I can't merge/push directly to this repo.

**Comment by bumblefudge** [comment]
Oh, good point-- the maintainers of every WG repo are the chairs of that WG by default.  If the fine folks at @didcomm-wg-chairs would rather a work item lead had maintainer rights, they can let me know here or in Slack and I will make it so like an old-timey djinn! 🧞‍♀️

**Pull request merged**
